---
#
# Let Encrypt Dependencies
#

- name: Update apt cache.
  apt: update_cache=true cache_valid_time=600
  when: ansible_os_family == 'Debian'
  changed_when: false

- name: Install dependencies (RedHat).
  yum: 
    name: ['cronie', "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"]
    state: present

- name: Install cron (Debian).
  apt: 
    name: cron 
    state: present
  when: ansible_os_family == 'Debian'

#
# Docker Dependencies
#

- name: Install Docker (Debian Family).
  block:
    - name: Add Docker Repository (Ubuntu).
      block:
        - name: Add Ubuntu Docker Key
          apt_key:
            id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        - name: Install Docker Repository (Ubuntu)
          apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present
      when: ansible_distribution == 'Ubuntu'
      #https://docs.docker.com/install/linux/docker-ce/ubuntu/

    - name: Add Docker Repository (Debian)
      block:
        - name: Add Debian Key
          apt_key:
            id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
            state: present
        - name: Install Docker Repository (Debian)
          apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
            state: present
      when: ansible_distribution == 'Debian'
      #https://docs.docker.com/install/linux/docker-ce/debian/

    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false

    - name: Install Docker Package
      apt: 
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present
  when: ansible_os_family == 'Debian'

- name: Install Docker (RedHat).
  block:
    - name: Install Yum Repo Tools
      yum:
        name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
        state: present

    - name: Install Docker Repo (RedHat).
      yum:
        name: 'https://download.docker.com/linux/centos/docker-ce.repo'
        state: present

    - name: Install Docker Packages (RedHat).
      yum:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present
  when: ansible_os_family == 'RedHat'