---
# tasks file for ansible-docker-keycloak


- name: Install Dependencies
  import_tasks: "{{ role_path }}/tasks/install_dependencies.yml"
  become: yes
  tags:
    - setup-all
    - setup-keycloak

- name: Setup Nginx
  import_tasks: "{{ role_path }}/tasks/setup_nginx.yml"
  become: yes
  tags:
    - setup-ngnix
    - setup-all

- name: Setup Docker
  import_tasks: "{{ role_path }}/tasks/setup_keycloak_docker.yml"
  become: yes
  tags:
    - setup-all
    - setup-keycloak

- name: Ensure Systemd Services Stopped
  systemd:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ keycloak_systemd_services_list }}"
  become: true
    - setup-all
    - setup-nginx
    - setup-keycloak
  
- name: Ensure No Nginx cache exists. Resolves Bad Gateway errors
  file:
    path: /var/cache/nginx
    state: absent
  tags:
    - always
    
- name: Ensure Systemd Services Started
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ keycloak_systemd_services_list }}"
  become: true
  tags:
    - setup-all
    - setup-keycloak
    - setup-nginx