---
# tasks file for ansible-docker-keycloak


- name: Install Dependencies
  import_tasks: "{{ role_path }}/tasks/install_dependencies.yml"
  become: true

- name: Setup Cert Bot
  import_tasks: "{{ role_path }}/tasks/setup_lets_encrypt.yml"
  become: true

- name: Setup Nginx
  import_tasks: "{{ role_path }}/tasks/setup_nginx.yml"
  become: true