---
# tasks file for ansible-docker-keycloak


- name: Install Dependencies
  import_tasks: "{{ role_path }}/tasks/install_dependencies.yml"
  become: yes

- name: Setup Cert Bot
  import_tasks: "{{ role_path }}/tasks/setup_lets_encrypt.yml"
  become: yes

- name: Setup Nginx
  import_tasks: "{{ role_path }}/tasks/setup_nginx.yml"
  become: yes

- name: Setup Docker
  import_tasks: "{{ role_path }}/tasks/setup_keycloak_docker.yml"
  become: yes

- name: Ensure Systemd Services Stopped
  systemd:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ keycloak_systemd_services_list }}"

- name: Ensure Systemd Services Started
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ keycloak_systemd_services_list }}"