---
# tasks file for ansible-docker-keycloak


- name: Install Dependencies
  import_tasks: "{{ role_path }}/tasks/install_dependencies.yml"
  become: yes
  tags:
    - setup-all

- name: Setup Cert Bot
  import_tasks: "{{ role_path }}/tasks/setup_lets_encrypt.yml"
  become: yes
  tags:
    - setup-all
    - setup-ssl

- name: Setup Nginx
  import_tasks: "{{ role_path }}/tasks/setup_nginx.yml"
  become: yes
  tags:
    - setup-all
    - setup-ngnix

- name: Setup Docker
  import_tasks: "{{ role_path }}/tasks/setup_keycloak_docker.yml"
  become: yes
  tags:
    - setup-all
    - setup-docker
