---
# tasks file for ansible-docker-keycloak
- name: init vars
  import_tasks: "{{ role_path }}/tasks/init.yml"
  become: yes
  tags:
    - always

- name: Install Dependencies
  import_tasks: "{{ role_path }}/tasks/install_dependencies.yml"
  become: yes
  tags:
    - setup-all
    - setup-keycloak

- name: Setup Nginx
  import_tasks: "{{ role_path }}/tasks/setup_nginx.yml"
  become: yes
  tags:
    - setup-ngnix
    - setup-all

- name: Setup Docker
  import_tasks: "{{ role_path }}/tasks/setup_keycloak_docker.yml"
  become: yes
  tags:
    - setup-all
    - setup-keycloak

- name: Setup Docker
  import_tasks: "{{ role_path }}/tasks/setup_postgres_docker.yml"
  become: yes
  tags:
    - setup-all
    - setup-postgres
  
- name: Ensure No Nginx cache exists. Resolves Bad Gateway errors
  file:
    path: /var/cache/nginx
    state: absent
  tags:
    - always
    
- name: Ensure Systemd Services retarted
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ keycloak_systemd_services_list }}"
  become: true
  tags:
    - setup-all
    - setup-keycloak
    - setup-nginx