---
## https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/SSL-on-amazon-linux-2.html
## https://github.com/geerlingguy/ansible-role-certbot/blob/master/molecule/default/playbook-standalone-nginx-aws.yml

- name: Create Lets Encrypt Certificates
  block:
    - name: Install Certs
      include_role:
        name: geerlingguy.certbot
      vars:
        certbot_admin_email: "{{ letsencrypt_certbot_admin_email }}"
        certbot_create_if_missing: "{{ letsencrypt_certbot_create_if_missing }}"
        certbot_create_standalone_stop_services: "{{ letsencrypt_certbot_create_standalone_stop_services }}"
        certbot_certs:
            - domains:
              - "{{ keycloak_domain_name }}"
        when: letsencrypt_certbot_enabled

    - name: Check that the cert.pem exists
      stat:
        path:  "/etc/letsencrypt/live/{{ keycloak_domain_name }}/cert.pem"
      register: cert_stat_result
    
    - name: Check that the privkey.pem exists
      stat:
        path:  "/etc/letsencrypt/live/{{ keycloak_domain_name }}/privkey.pem"
      register: privkey_stat_result

    - name: Set files
      set_fact:
        keycloak_cert_directory: "/etc/letsencrypt/live/{{ keycloak_domain_name }}"
        keycloak_tls_cert: "/etc/letsencrypt/live/{{ keycloak_domain_name }}/cert.pem"
        keycloak_tls_key: "/etc/letsencrypt/live/{{ keycloak_domain_name }}/privkey.pem"
      when: privkey_stat_result.stat.exists == true and cert_stat_result.stat.exists
      
    - name: Symbolic Link SSL Certificates
      block:
        - name: Ensure Ngnix Path Exists
          file:
            path: "/etc/ssl/nginx/"
            state: directory
            mode: 0770
            owner: "{{ root }}"
            group: "{{ root }}"

        - name: Symlink SSL Certificate
          file:
            src: "{{ keycloak_tls_cert }}"
            dst: "/etc/ssl/nginx/nginx-repo.crt"
            state: link

        - name: Symlink SSL Keys
          file:
            src: "{{ keycloak_tls_key }}"
            dst: "/etc/ssl/nginx/nginx-repo.key"
            state: link
      when: privkey_stat_result.stat.exists == true and cert_stat_result.stat.exists
      