- fail: msg="Bailing out. this play requires 'keycloak_postgres_connection_username'"
  when: keycloak_postgres_connection_username is undefined

- name: Pull Postgres Docker
  docker_image:
    name: "{{ keycloak_postgres_docker_image }}"
    source: pull
  when: keycloak_postgres_enabled|bool

- name: Ensure Install Postgres Directory Exists
  file: 
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0750'
  with_items:
    - "{{ keycloak_postgres_base_path }}"
    - "{{ keycloak_postgres_data_path }}"
  when: keycloak_postgres_enabled|bool

- name: Ensure postgres.service installed
  template:
    src: "{{ role_path }}/templates/postgres.service.j2"
    dest: "{{ keycloak_systemd_path }}/postgres.service"
    mode: 0644
  register: postgres_systemd_service_result
  when: keycloak_postgres_enabled|bool

- name: Ensure postgres setting files are installed
  template:
    src: "{{ role_path }}/templates/env-postgres-psql.j2"
    dest: "{{ keycloak_postgres_base_path }}/env-postgres-psql"
    mode: 0644
  register: postgres_systemd_service_result
  when: keycloak_postgres_enabled|bool

- name: Ensure systemd reloaded after postgres.service installation
  service:
    daemon_reload: yes
  when: "postgres_systemd_service_result.changed"

- name: Ensure postgres.service doesn't exist
  file:
    path: "{{ keycloak_systemd_path }}/postgres.service"
    state: absent
  when: not keycloak_postgres_enabled|bool