---
#
# https://hub.docker.com/r/jboss/keycloak/tags
#

- fail: msg="Bailing out. this play requires 'keycloak_admin_password'"
  when: keycloak_admin_password is undefined

- name: Pull Keycloak Docker
  docker_image:
    name: "{{ keycloak_docker_image }}"
    source: pull

- name: Ensure Install Directory Exists
  file: 
    path: "{{ keycloak_install_directory }}"
    state: directory
    owner: "{{ keycloak_user_uid }}"
    group: "{{ keycloak_user_gid }}"
    mode: 0750
  

- name: Ensure keycloak.service installed
  template:
    src: "{{ role_path }}/templates/keycloak.service.j2"
    dest: "{{ keycloak_systemd_path }}/keycloak.service"
    mode: 0640
  register: keycloak_systemd_service_result


- name: Ensure systemd reloaded after keycloak.service installation
  systemd:
    daemon_reload: yes
  when: "keycloak_systemd_service_result.changed"