---
## https://github.com/nginxinc/ansible-role-nginx
##
##


- name: Install Nginx
  block:
    - name: update apt cache
      apt: update_cache=true cache_valid_time=600
      changed_when: false
      when: ansible_os_family == 'Debian'
      
    - name: Install Ngnix
      include_role: 
        name: hispanico.nginx-revproxy
      vars:
        nginx_revproxy_sites:
          default:
            ssl: false
            letsencrypt: false

          keycloak:
            domains:
              - "{{ keycloak_domain_name }}"
            upstreams:
              - { backend_address: localhost, backend_port: 8442 }
            listen: 80
            listen_ssl: 8443
            ssl: true
            letsencrypt: true
            letsencrypt_email: "{{ letsencrypt_certbot_admin_email }}"
